### ISSUE TITLE
Cannot read file with 0 in the file name.

### ISSUE THREAD

**Issue by gsangeryee** [Picodes/4naly3er#8]
The tool cannot read files with `0` in the file name. Such as `contracts/lending/tokens/cErc20ModifiedDelegator.sol`, `contracts/lending/tokens/cToken/CErc20.sol`

In the [src/index.ts#L32](https://github.com/Picodes/4naly3er/blob/658b449c985377e1a1ddb94d18c88e76207f7784/src/index.ts#L32)

```solidity
    for (const word of [...content.matchAll(/[a-zA-Z\/\.\-\_1-9]+/g)].map(r => r[0])) {
```

Suggestion:

```solidity
    for (const word of [...content.matchAll(/[a-zA-Z\/\.\-\_0-9]+/g)].map(r => r[0])) {
```

**Comment by Picodes** [comment]
Thanks for reporting!
